name: EPS CI/CD for development environment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  workflow_dispatch:


# Workflow for building, backing up and deploying the Project
jobs:

  # This workflow is about building the application
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Set Java
    env:
      JAVA_HOME: /app/onestopd/jdk

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Build the project
      - name: Build the project
        run: ./gradlew clean build -x test

  copy-jar:
    needs: build
    runs-on: self-hosted

    # Set Deploy directory
    env:
      DEPLOY_DIR: /app/onestopd/onestopshopv2/cicd-runner

    steps:
      # Copy Jar to deploy location with new name so it doesn't overwrite running jar
      - name: Copy Jar
        run: cp build/libs/demo-0.0.1-SNAPSHOT.jar $DEPLOY_DIR/demo-0.0.1-SNAPSHOT_new.jar

  backup:
    needs: copy-jar
    runs-on: self-hosted
    defaults:
      # Change working directory for all steps
      run:
        working-directory: /app/onestopd/onestopshopv2/cicd-runner
    steps:
      # Delete backup
      - name: Delete backup
        run: |
          if [ -e demo-0.0.1-SNAPSHOT_bk.jar ]; then
            rm demo-0.0.1-SNAPSHOT_bk.jar
          fi

      # Backup old jar
      - name: Backup old jar
        run: |
          if [ -e demo-0.0.1-SNAPSHOT.jar ]; then
            mv demo-0.0.1-SNAPSHOT.jar demo-0.0.1-SNAPSHOT_bk.jar
          fi

      # Rename new jar
      - name: Rename new jar
        run: |
          if [ -e demo-0.0.1-SNAPSHOT_new.jar ]; then
            mv demo-0.0.1-SNAPSHOT_new.jar demo-0.0.1-SNAPSHOT.jar
          fi

  deploy:
    needs: backup
    runs-on: self-hosted
    defaults:
      # Change working directory for all steps
      run:
        working-directory: /app/onestopd/onestopshopv2/cicd-runner
    steps:
      # Restart application
      # RUNNER_TRACKING_ID added because cleanup will kill orphan processes
      - name: Run new jar
        run: |
          if [ -e demo-0.0.1-SNAPSHOT.jar ]; then
            RUNNER_TRACKING_ID="" && ./iamservices.sh restart demo-0.0.1-SNAPSHOT.jar
          fi


