# This is a basic workflow to help you get started with Actions

name: DC1 CI/CD for production environment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ main ]
  workflow_dispatch:


# DC1 workflow for building, testing and scanning the DC1 Project
jobs:

  # This workflow is about building the application
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Set Java
    env:
      JAVA_HOME: /app/onestopd/jdk

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Build the project
      - name: Build the project
        run: ./gradlew clean build -x test

  copy-jar:
    needs: build

    # The type of runner that the job will run on
    runs-on: self-hosted

    # Set Deploy directory
    env:
      DEPLOY_DIR: /app/onestopd/onestopshopv2/cicd-runner

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Copy Jar
      - name: Copy Jar
        run: cp build/libs/demo-0.0.1-SNAPSHOT.jar $DEPLOY_DIR/demo-0.0.1-SNAPSHOT_new.jar

  deploy:
    needs: copy-jar

    # The type of runner that the job will run on
    runs-on: self-hosted

    # Set Deploy directory
    env:
      DEPLOY_DIR: /app/onestopd/onestopshopv2/cicd-runner

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Change directory
      - name: Change directory
        run: cd $DEPLOY_DIR

      # Delete backup
      - name: Delete backup
        if: ${{ -f demo-0.0.1-SNAPSHOT_bk.jar }}
        run: rm demo-0.0.1-SNAPSHOT.jar

      # Rename old jar
      - name: Rename old jar
        if: ${{ -f demo-0.0.1-SNAPSHOT.jar }}
        run: rename demo-0.0.1-SNAPSHOT.jar demo-0.0.1-SNAPSHOT_bk.jar

      # Rename new jar
      - name: Rename new jar
        if: ${{ -f demo-0.0.1-SNAPSHOT_new.jar }}
        run: rename demo-0.0.1-SNAPSHOT_new.jar demo-0.0.1-SNAPSHOT.jar

      # Run new jar
      - name: Run new jar
        run: ./iamservices.sh restart demo-0.0.1-SNAPSHOT.jar


